cursor #cdd6f4
cursor_text_color #a6adc8

foreground            #cdd6f4
background            #1e1e2e
selection_foreground  #1e1e2e
selection_background  #eba0ac
url_color             #f38ba8

color0   #181825
color1   #ff7277
color2   #97f379
color3   #ffe272
color4   #e67091
color5   #701830
color6   #f38ba8
color7   #ffeff3
color8   #9d9295
color9   #ff9fa2
color10  #bbffa5
color11  #ffeca5
color12  #ffa2bc
color13  #ffb2c7
color14  #ffcddb
color15  #fff8fa
